services:
  runner1:
    build:
      context: .
    environment:
      - TOKEN=${TOKEN}
      - RUNNER_NAME=runner1

  runner2:
    build:
      context: .
    environment:
      - TOKEN=${TOKEN}
      - RUNNER_NAME=runner2

  runner3:
    build:
      context: .
    environment:
      - TOKEN=${TOKEN}
      - RUNNER_NAME=runner3
