services:
  runner1:
    image: docker.io/library/github-actions-runner
#     build:
#       context: .
    environment:
      - RUNNER_NAME=runner1
    env_file:
      - ./env
    user: "1000:986"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  runner2:
    image: docker.io/library/github-actions-runner
#     build:
#       context: .
    environment:
      - RUNNER_NAME=runner2
    env_file:
      - ./env
    user: "1000:986"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  runner3:
    image: docker.io/library/github-actions-runner
#     build:
#       context: .
    environment:
      - RUNNER_NAME=runner3
    env_file:
      - ./env
    user: "1000:986"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
