services:
  runner1:
    build:
      context: .
    environment:
      - RUNNER_NAME=runner1
    user: "1000:986"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  runner2:
    build:
      context: .
    environment:
      - RUNNER_NAME=runner2
    user: "1000:986"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  runner3:
    build:
      context: .
    environment:
      - RUNNER_NAME=runner3
    user: "1000:986"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
