name: CI Reusable
on:
  workflow_call:
    inputs:
      component_name:
        required: true
        type: string

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v7
      - run: |
          make docker-build

  scan:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v7
      - run: |
          echo make docker-scan

  publish:
    needs: scan
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v7
      - run: make docker-push

  dev-deploy:
    needs: publish
    runs-on: self-hosted
    steps:
      - name: Checkout helm repo
        uses: actions/checkout@v7
        with:
          repository: raghudevopsb89/roboshop-helm-v1
          path: helm
      - run: |
          cd helm
          #make upgrade component_name=${{ inputs.component_name }} github_sha=${GITHUB_SHA} cluster_env=dev
          echo az aks get-credentials --resource-group denmark-east-dev --name roboshop-dev --overwrite-existing
          az aks get-credentials --resource-group denmark-east-dev --name roboshop-dev --overwrite-existing
          pass=$(kubectl get secret argocd-initial-admin-secret -o  jsonpath='{.data.password}' | base64 -d)
          argocd login argocd-dev.rdevopsb89.online --username admin --password ${pass} --insecure
          argocd app create ${{ inputs.component_name }} --repo https://github.com/raghudevopsb89/roboshop-helm-v1 --path . --dest-namespace roboshop --dest-server https://kubernetes.default.svc --helm-set github_sha=${GITHUB_SHA} --values values/${{ inputs.component_name }}.yml

  qa-deploy:
    needs: dev-deploy
    runs-on: self-hosted
    environment: qa
    steps:
      - name: Checkout helm repo
        uses: actions/checkout@v7
        with:
          repository: raghudevopsb89/roboshop-helm-v1
          path: helm
      - run: |
          echo cd helm
          echo make upgrade component_name=${{ inputs.component_name }} github_sha=${GITHUB_SHA} cluster_env=qa

  uat-deploy:
    needs: qa-deploy
    runs-on: self-hosted
    environment: uat
    steps:
      - name: Checkout helm repo
        uses: actions/checkout@v7
        with:
          repository: raghudevopsb89/roboshop-helm-v1
          path: helm
      - run: |
          echo cd helm
          echo make upgrade component_name=${{ inputs.component_name }} github_sha=${GITHUB_SHA} cluster_env=uat

  prod-deploy:
    needs: uat-deploy
    runs-on: self-hosted
    environment: prod
    steps:
      - name: Checkout helm repo
        uses: actions/checkout@v7
        with:
          repository: raghudevopsb89/roboshop-helm-v1
          path: helm
      - run: |
          echo cd helm
          echo make upgrade component_name=${{ inputs.component_name }} github_sha=${GITHUB_SHA} cluster_env=prod


